# Preliminaries

In [26]:
# importing packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

In [5]:
# importing the challenge data
import os
owd = os.getcwd()
data_dir = "C:\\Users\\chin.kwan\\OneDrive - IFRC\\Desktop\\fdrs_imputation_2.0\\challenge_data"
os.chdir(data_dir)

# training set
train_data_files = os.listdir(data_dir)[:-4]
train_data = pd.DataFrame()

for file in train_data_files:
    chal_data = pd.read_csv(file)
    
    # Pivoting challenge data into wide format
    chal_data = chal_data.pivot(index = ['doncode', 'year'], 
                                columns = "kpi", values = "value")
    train_data = pd.concat([train_data, chal_data])
    
train_data.head()

# # Adding ISO3 code
# ns_data = pd.read_csv("ns_data.csv")
# train_data = train_data.merge(ns_data[["KPI_DON_code", "iso_3"]], how = "left", left_on = "doncode", right_on = "KPI_DON_code")

C:\Users\chin.kwan\OneDrive - IFRC\Desktop\fdrs_imputation_2.0\challenge_data

In [28]:
# test set
test_data = pd.read_csv("challenge_data_2022.csv")
test_data = test_data.pivot(index = ["doncode", "year"], 
                            columns = "kpi", values = "value")
test_data.head()

,kpi,KPI_ClimateHeat_CPD,KPI_Climate_CPD,KPI_DonBlood_Tot,KPI_IncomeLC_CHF,KPI_PStaff_Tot,KPI_PeopleVol_Tot,KPI_ReachCTP_CPD,KPI_ReachDRER_CPD,KPI_ReachDRR_CPD,KPI_ReachHI_CPD,...,KPI_ReachLTSPD_CPD,KPI_ReachL_CPD,KPI_ReachM_CPD,KPI_ReachRCRCEd_CPD,KPI_ReachSI_CPD,KPI_ReachS_CPD,KPI_ReachWASH_CPD,KPI_TrainFA_Tot,KPI_expenditureLC_CHF,KPI_noLocalUnits
doncode,year,,,,,,,,,,,,,,,,,,,,,
DAD001,2022,72.0,NaN,1450.0,2684166.0,51.0,318.0,NaN,NaN,NaN,NaN,...,564.0,NaN,187.0,14.0,NaN,NaN,NaN,3582.0,2595220.0,1.0
DAE001,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DAF001,2022,NaN,NaN,780.0,22720988.0,3909.0,24056.0,316005.0,2048776.0,NaN,416679.0,...,3382377.0,1445389.0,NaN,225.0,NaN,70062.0,63003.0,73.0,21541408.0,122.0
DAG001,2022,NaN,NaN,NaN,169478.0,7.0,83.0,NaN,NaN,NaN,NaN,...,25.0,NaN,1.0,NaN,NaN,11.0,14.0,152.0,154862.0,3.0
DAL001,2022,4000.0,0.0,4895.0,2545650.0,62.0,2225.0,5000.0,25000.0,20000.0,27300.0,...,15400.0,5000.0,485.0,20400.0,7800.0,100.0,2250.0,71638.0,1544930.0,39.0

In [29]:
# Changing back to original directory
os.chdir(origin_dir)
os.getcwd()

'C:\\Users\\chin.kwan\\OneDrive - IFRC\\Desktop\\fdrs_imputation_2.0\\challenge_data'

# EDA

In [15]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2401 entries, ('DAD001', 2010) to ('DZM001', 2021)
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   KPI_ClimateHeat_CPD    89 non-null     float64
 1   KPI_Climate_CPD        108 non-null    float64
 2   KPI_DonBlood_Tot       1562 non-null   float64
 3   KPI_IncomeLC_CHF       1842 non-null   float64
 4   KPI_PStaff_Tot         1892 non-null   float64
 5   KPI_PeopleVol_Tot      1967 non-null   float64
 6   KPI_ReachCTP_CPD       764 non-null    float64
 7   KPI_ReachDRER_CPD      1228 non-null   float64
 8   KPI_ReachDRR_CPD       884 non-null    float64
 9   KPI_ReachHI_CPD        148 non-null    float64
 10  KPI_ReachHPM_CPD       191 non-null    float64
 11  KPI_ReachH_CPD         934 non-null    float64
 12  KPI_ReachLTSPD_CPD     1137 non-null   float64
 13  KPI_ReachL_CPD         794 non-null    float64
 14  KPI_ReachM_CPD         779 non-null    float64
 15  KPI_ReachRCRCEd_CPD    142 non-null    float64
 16  KPI_ReachSI_CPD        787 non-null    float64
 17  KPI_ReachS_CPD         702 non-null    float64
 18  KPI_ReachWASH_CPD      822 non-null    float64
 19  KPI_TrainFA_Tot        1020 non-null   float64
 20  KPI_expenditureLC_CHF  1830 non-null   float64
 21  KPI_noLocalUnits       1937 non-null   float64
dtypes: float64(22)
memory usage: 425.8+ KB

In [16]:
train_data.describe()

kpi,KPI_ClimateHeat_CPD,KPI_Climate_CPD,KPI_DonBlood_Tot,KPI_IncomeLC_CHF,KPI_PStaff_Tot,KPI_PeopleVol_Tot,KPI_ReachCTP_CPD,KPI_ReachDRER_CPD,KPI_ReachDRR_CPD,KPI_ReachHI_CPD,...,KPI_ReachLTSPD_CPD,KPI_ReachL_CPD,KPI_ReachM_CPD,KPI_ReachRCRCEd_CPD,KPI_ReachSI_CPD,KPI_ReachS_CPD,KPI_ReachWASH_CPD,KPI_TrainFA_Tot,KPI_expenditureLC_CHF,KPI_noLocalUnits
count,89.000000,1.080000e+02,1.562000e+03,1.842000e+03,1892.000000,1.967000e+03,7.640000e+02,1.228000e+03,8.840000e+02,1.480000e+02,...,1.137000e+03,7.940000e+02,7.790000e+02,1.420000e+02,7.870000e+02,7.020000e+02,8.220000e+02,1.020000e+03,1.830000e+03,1937.000000
mean,11589.674157,7.871353e+04,1.609785e+05,1.666328e+08,2686.448203,7.707104e+04,4.794087e+04,1.018551e+06,2.582461e+05,3.974150e+05,...,9.218472e+05,1.625756e+05,5.310402e+04,7.882740e+04,1.432541e+05,8.274435e+04,3.491261e+05,9.019239e+04,1.635954e+08,850.564791
std,37176.503655,3.601665e+05,7.256321e+05,9.840332e+08,14056.221126,3.269363e+05,2.958123e+05,1.305372e+07,9.502886e+05,9.554059e+05,...,2.626102e+06,7.582515e+05,3.114211e+05,5.132339e+05,7.494437e+05,5.513584e+05,1.317757e+06,4.312595e+05,9.725451e+08,6933.351566
min,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
25%,0.000000,0.000000e+00,0.000000e+00,6.207668e+05,45.000000,1.496000e+03,0.000000e+00,1.231500e+03,8.420000e+02,3.265000e+02,...,4.450000e+03,1.825000e+01,0.000000e+00,3.400000e+01,4.500000e+01,0.000000e+00,1.290000e+02,8.930000e+02,5.956838e+05,15.000000
50%,0.000000,7.785000e+02,4.235000e+02,2.440032e+06,192.000000,6.330000e+03,1.198500e+03,2.005850e+04,1.357950e+04,3.816000e+04,...,7.206200e+04,5.088500e+03,1.825000e+03,2.293000e+03,3.405000e+03,3.250000e+02,1.994700e+04,4.034500e+03,2.283788e+06,54.000000
75%,904.000000,1.584900e+04,2.741750e+04,1.397891e+07,791.250000,2.571000e+04,1.052300e+04,1.507305e+05,1.247850e+05,3.624210e+05,...,5.356940e+05,5.183000e+04,1.585000e+04,2.516700e+04,3.279100e+04,7.872750e+03,1.547175e+05,3.113975e+04,1.266991e+07,185.000000
max,204838.000000,2.575739e+06,1.674500e+07,1.192399e+10,189787.000000,6.081957e+06,4.867197e+06,4.397319e+08,1.137097e+07,9.201557e+06,...,4.521790e+07,9.417554e+06,4.870858e+06,6.059998e+06,1.141811e+07,6.475298e+06,1.460000e+07,6.190964e+06,1.194927e+10,122933.000000

In [17]:
# Ratio of missing data
round(np.mean(train_data.isna(), axis = 0), 2)

kpi
KPI_ClimateHeat_CPD      0.96
KPI_Climate_CPD          0.96
KPI_DonBlood_Tot         0.35
KPI_IncomeLC_CHF         0.23
KPI_PStaff_Tot           0.21
KPI_PeopleVol_Tot        0.18
KPI_ReachCTP_CPD         0.68
KPI_ReachDRER_CPD        0.49
KPI_ReachDRR_CPD         0.63
KPI_ReachHI_CPD          0.94
KPI_ReachHPM_CPD         0.92
KPI_ReachH_CPD           0.61
KPI_ReachLTSPD_CPD       0.53
KPI_ReachL_CPD           0.67
KPI_ReachM_CPD           0.68
KPI_ReachRCRCEd_CPD      0.94
KPI_ReachSI_CPD          0.67
KPI_ReachS_CPD           0.71
KPI_ReachWASH_CPD        0.66
KPI_TrainFA_Tot          0.58
KPI_expenditureLC_CHF    0.24
KPI_noLocalUnits         0.19
dtype: float64

In [18]:
# Number of missing values per KPI
np.sum(train_data.isna(), axis = 0)

kpi
KPI_ClimateHeat_CPD      2312
KPI_Climate_CPD          2293
KPI_DonBlood_Tot          839
KPI_IncomeLC_CHF          559
KPI_PStaff_Tot            509
KPI_PeopleVol_Tot         434
KPI_ReachCTP_CPD         1637
KPI_ReachDRER_CPD        1173
KPI_ReachDRR_CPD         1517
KPI_ReachHI_CPD          2253
KPI_ReachHPM_CPD         2210
KPI_ReachH_CPD           1467
KPI_ReachLTSPD_CPD       1264
KPI_ReachL_CPD           1607
KPI_ReachM_CPD           1622
KPI_ReachRCRCEd_CPD      2259
KPI_ReachSI_CPD          1614
KPI_ReachS_CPD           1699
KPI_ReachWASH_CPD        1579
KPI_TrainFA_Tot          1381
KPI_expenditureLC_CHF     571
KPI_noLocalUnits          464
dtype: int64

# Imputing missing data

In [19]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [20]:
# Setting up baseline
iter_imp = IterativeImputer(random_state=123, 
                            max_iter=int(1e4))
train_imp = iter_imp.fit_transform(train_data)

In [21]:
# Imputing on 2022 data
test_imp = iter_imp.transform(test_data)

# Converting to DataFrame
test_imp_df = pd.DataFrame(test_imp, index = test_data.index, columns = test_data.columns).reset_index()

# Wide to long format
test_imp_df = pd.melt(test_imp_df, id_vars = ["doncode", 'year'])
test_imp_df.head()

# Writing to csv 
test_imp_df.to_csv("Baldur_2022_predictions.csv")